$enc = new-object System.Text.UTF8Encoding $false
$old = [System.IO.File]::ReadAllText('data-tests.js', $enc)

$old = $old.Replace('â€”', '—')
$old = $old.Replace('ğŸŒ±', '🌱')
$old = $old.Replace('ğŸŒ¿', '🌿')
$old = $old.Replace('ğŸŒ³', '🌳')
$old = $old.Replace('ğŸ–¼ï¸', '🖼️')
$old = $old.Replace('ğŸ“ ', '📝')
$old = $old.Replace('Ã¼', 'ü')
$old = $old.Replace('Ã¶', 'ö')
$old = $old.Replace('Ã¤', 'ä')
$old = $old.Replace('ÃŸ', 'ß')
$old = $old.Replace('Ã–', 'Ö')
$old = $old.Replace('ğŸŽ§', '🎧')
$old = $old.Replace('â€˜', '‘')
$old = $old.Replace('â€™', '’')
$old = $old.Replace('â€œ', '“')
$old = $old.Replace('â€ ', '”')
$old = $old.Replace('ğŸ›‚', '🛂')
$old = $old.Replace('ğŸ”¬', '🔬')
$old = $old.Replace('ğŸ ›ï¸', '🏛️')
$old = $old.Replace('ğŸ ¥', '🏥')
$old = $old.Replace('ğŸ Ž', '🍎')
$old = $old.Replace('ğŸ ±', '🐱')
$old = $old.Replace('ğŸ  ', '🏠')
$old = $old.Replace('â˜€ï¸ ', '☀️')
$old = $old.Replace('ğŸš—', '🚗')
$old = $old.Replace('ğŸ“…', '📅')
$old = $old.Replace('ğŸ Œ', '🍌')
$old = $old.Replace('ğŸ“š', '📚')
$old = $old.Replace('ğŸ’§', '💧')
$old = $old.Replace('ğŸ‘¨â€ âš•ï¸ ', '👨‍⚕️')
$old = $old.Replace('â °', '⌛')
$old = $old.Replace('ğŸ’Š', '💊')
$old = $old.Replace('ğŸŒ§ï¸ ', '🌧️')
$old = $old.Replace('ğŸ§‘â€ ğŸ ³', '🧑‍🍳')
$old = $old.Replace('ğŸ “', '🍓')
$old = $old.Replace('âš½', '⚽')
$old = $old.Replace('â „ï¸ ', '❄️')
$old = $old.Replace('ğŸ «', '🏫')
$old = $old.Replace('ğŸš²', '🚲')
$old = $old.Replace('ğŸ ‚', '🍂')
$old = $old.Replace('âœ ï¸ ', '✏️')
$old = $old.Replace('ğŸ©º', '🩺')
$old = $old.Replace('ğŸŽ“', '🎓')
$old = $old.Replace('ğŸ”¥', '🔥')
$old = $old.Replace('ğŸ“œ', '📜')
$old = $old.Replace('ğŸ’¼', '💼')
$old = $old.Replace('ğŸ’µ', '💵')
$old = $old.Replace('ğŸŒŽ', '🌎')

$a1 = [System.IO.File]::ReadAllText('..\..\brain\be1ecf5c-3463-4958-b2ad-bcd2d452e75a\scratch\a1_tests.js', $enc)
$a2 = [System.IO.File]::ReadAllText('..\..\brain\be1ecf5c-3463-4958-b2ad-bcd2d452e75a\scratch\a2_tests.js', $enc)
$b1 = [System.IO.File]::ReadAllText('..\..\brain\be1ecf5c-3463-4958-b2ad-bcd2d452e75a\scratch\b1_tests.js', $enc)
$b2 = [System.IO.File]::ReadAllText('..\..\brain\be1ecf5c-3463-4958-b2ad-bcd2d452e75a\scratch\b2_tests.js', $enc)

$merged = $old.Replace("};
};", "},
" + $a1 + "
" + $a2 + "
" + $b1 + "
" + $b2 + "
};")
[System.IO.File]::WriteAllText('data-tests.js', $merged, $enc)